// // text_en.js

const textStrings = {
    TXT1: 'Phone Numbers',
    TXT2: 'Are you sure you want to remove this number?',
    TXT3: 'Add Phone Number',
    TXT4: 'phone',
    TXT5: 'numeric',
    TXT6: '• The baggage information is just for reference. Please check with airline for more specific information.',
    TXT7: 'Hand Baggage',
    TXT8: ' • Infant Baggage',
    TXT9: ': Airlines permits only one (1pc) bag weighing not more than 7 KGS. In addition to the one piece of Hand Baggage permitted, few airlines may permit Customer to carry one additional personal article such as a ladies purse or a small bag containing a laptop not weighing more than 3 KGS.',
    TXT10: ': Passenger traveling with infant are allowed to carry 1 Pc of additional Hand Baggage not exceeding 7 KGS.',
    TXT11: 'Baggage Disclaimer',
    TXT12: 'Check In Baggage',
    TXT13: '15 Kg (1 piece Only)',
    TXT14: '7 Kg Each Adult',
    TXT15: 'About This Property',
    TXT16: 'Unnamed Amenities',
    TXT17: 'Directions',
    TXT18: 'Book',
    TXT19: 'Check-In',
    TXT20: 'Highlights',
    TXT21: 'Amenities',
    TXT22: 'Property Rules',   
    TXT23: 'Cancellation Policy',
    TXT24: 'Reviews',
    TXT25: 'Nearby Properties',
    TXT26: 'Similar Properties',
    TXT27: 'Profile',
    TXT28: 'Personal Information',
    TXT29: 'Financial Information',
    TXT30: 'Government Id',
    TXT31: 'Company Information',
    TXT32: 'Seller Information',
    TXT33: 'Orders',
    TXT34: 'Shopping',
    TXT35: 'Travel',
    TXT36: 'Food',
    TXT37: 'Health',
    TXT38: 'Others',
    TXT39: 'Total Spends',
    TXT40: 'Weekly',
    TXT41: 'Monthly',
    TXT42: 'Yearly',
    TXT43: 'Order status summary',
    TXT44: 'Preparing your order',
    TXT45: 'Shipped',
    TXT46: ' Out for Delivery',
    TXT47: 'Confirmed',
    TXT48: 'See Details',
    TXT49: 'Report',
    TXT50: 'Analytics',
    TXT51: 'Your Chats',
    TXT52: 'Inbox',
    TXT53: 'Netflix',
    TXT54: 'Flipkart',
    TXT55: 'Amazon',

};

export default textStrings;